messages:
  tool:
    name: Oxidizer
    lore: []
  command:
    reload:
      success: "&aConfiguration reloaded"
    tool:
      success: "&aOxidizer tool given"
      failed: "&cFailed to give oxidizer tool"
    only-player: "&cThis command can be executed only by player"
  on-fail: "&cUnknown error using tool"

# Enables deoxidize behaviour on left click
deoxidizer: true
# Item type used for tool
tool_item: "minecraft:breeze_rod"
# Enables oxidation state cycling.
cycle: false
