lang:
  tool:
    name: Oxidizer
    lore: [
      "&6Right-click to increase oxidation stage",
      "&6Left-click to decrease oxidation stage"
    ]
  command:
    reload:
      success: "&aConfiguration reloaded"
    tool:
      success: "&aOxidizer tool given"
      failed: "&cFailed to give oxidizer tool"
    only-player: "&cThis command can be executed only by player"
  on-fail: "&cUnknown error using tool"

tool:
  # Enables oxidation decrease on left click
  deoxidize: true
  # Item type used for tool
  material: "minecraft:breeze_rod"
  # Enables oxidation state cycling.
  cycle_oxidation: false
